# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0002_auto_20170420_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now=True)),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
    ]
