# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 20:29
from __future__ import unicode_literals

import assinatura.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinatura', '0003_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='entregue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documento',
            name='recibo',
            field=models.FileField(blank=True, default=True, upload_to=assinatura.models.scramble_assinatura_filename),
        ),
    ]
